### ISSUE TITLE
Improve examples in Python API documentation

### ISSUE THREAD

**Issue by patrickkwang** [NCATSTranslator/reasoner-validator#1]
https://reasoner-validator.readthedocs.io/en/latest/reasoner_validator.html

Right now all of the example objects are `{'message': {}}`. Instead we should adopt the examples from the [Reasoner API schema](https://github.com/NCATS-Tangerine/NCATS-ReasonerStdAPI/blob/master/API/TranslatorReasonersAPI.yaml), and/or dynamically generate more appropriate ones.

**Comment by RichardBruskiewich** [comment]
Review https://reasoner-validator.readthedocs.io/en/latest/index.html#typical-output and see if any further "example objects" will be helpful. Maybe embed some of them into the OpenAPI example sections of the schema

**Comment by RichardBruskiewich** [comment]
https://reasoner-validator.readthedocs.io/en/latest/reasoner_validator.html is deprecated.  @patrickkwang (cc: @maximusunc ).  Maybe you can delete this particular readthedocs site? I don't have access to it.

Latest document site is: https://ncatstranslator.github.io/reasoner-validator/ which has enhanced examples. Probably still has room for improvement but it likely sufficiently detailed for more peoples' purposes.

**Comment by KevinBretonnelCohen** [comment]
Hi, can you remove me from this list, please?

Envoyé de mon iPad

**Comment by RichardBruskiewich** [comment]
> Hi, can you remove me from this list, please? Envoyé de mon iPad

Hi @KevinBretonnelCohen, I haven't ever explicitly put you on this list. Probably seeing this stuff via @NCATSTranslator/all-translator. Ask them to remove you from that list to stop all Translator Git notifications, not just from this project.

**Comment by sierra-moxon** [comment]
@sstemann was able to remove him.  I'll avoid tagging again to notify. :)
