### ISSUE TITLE
Query Graph Validation

### ISSUE THREAD

**Issue by kennethmorton** [NCATSTranslator/reasoner-validator#14]
As making queries is one of the more difficult aspects of the current translator, I believe we could do better validation of the graph. Although this may not technically validate the JSON schema, it isn't really a useful query. A number of notable issues exist.
 
- [x] No valid node information
- [x] An edge that does not point to existing nodes (now seems related to https://github.com/NCATSTranslator/reasoner-validator/issues/74)
- [x] A predicate that contains "biolink:" but is not a valid predicate

```json
{
  "version": "1.2",
  "message": {
    "query_graph": {
        "nodes": {
            "drug": {}
        },
        "edges": {
            "treats": {"subject": "not_here", "predicates": ["biolink:not_a_real_predicate"], "object": "also_not_here"}
        }
    }
  }
}
```

**Comment by RichardBruskiewich** [comment]
> * No valid node information

Hi @kennethmorton, the TRAPI model for a `QNode` is [here](https://github.com/NCATSTranslator/ReasonerAPI/blob/master/TranslatorReasonerAPI.yaml#L586) and seems to allow node specifications like: 

"drug": {}

When you mention '_no valid node information_', what should we be checking for?

The other two use cases might already be implemented in the package's [query graph validation method](https://github.com/NCATSTranslator/reasoner-validator/blob/master/reasoner_validator/biolink/__init__.py#L489).

**Comment by kennethmorton** [comment]
Yeah! Somethings need to be true to have a valid query but can't be represented and validated purely by the JSON schema. 

I am not sure I have a complete handle on everything one would need to check in general but for the things I listed above.

* At least one node in the qraph needs to be bound in some way. Typically by category or id. In general (but not always) at least one node is bound by id and all others are bound by category.
* All of the IDs used in the qedge subject and object must correspond to qnodes
* predicates should be valid biolink predicates

**Comment by RichardBruskiewich** [comment]
>     * All of the IDs used in the qedge subject and object must correspond to qnodes

I've now implemented the detection of uninformative QNodes (validation message  code: **error.query_node.nodes.uninformative** in commit #a7f367d). 

The **error.query_graph.edge.subject.missing_from_nodes** and **error.query_graph.edge.subject.missing_from_nodes** were actually implemented some time ago, so I think this issue is now been fully resolved.
