### ISSUE TITLE
Add validation for 'canonical' predicates

### ISSUE THREAD

**Issue by RichardBruskiewich** [NCATSTranslator/reasoner-validator#22]
We need to check if TRAPI knowledge graphs (input query graphs too?) returned by KP (and ARA's), are using the 'canonical' predicates

**Comment by edeutsch** [comment]
Agreed, all instances of predicates, both QG and KP should be checked for Biolink compliance.
Maybe we can start here as an easy first step.

**Comment by RichardBruskiewich** [comment]
Actually, for both QG and KP,  the code already checks for the existence of predicates against a specified Biolink Model (note: every test run has either an assumed default BMT or a user-specified model version). Beyond that, we don't really additional compliance checking. This issue suggests the addition of a test for 'canonical' direction.

**Comment by RichardBruskiewich** [comment]
Resolved by a80f34604fdb1c9af5ce26a0acaec89702994da2
