### ISSUE TITLE
Support for TRAPI v1.3-beta

### ISSUE THREAD

**Issue by edeutsch** [NCATSTranslator/reasoner-validator#23]
I was about to implement validation in ARAX for TRAPI 1.3 beta, but before doing so I was informed that the current validator in PyPI does not permit version numbers with a hyphen, i.e. v1.3-beta

It would be very useful to support v1.3-beta as soon as possible:
https://github.com/NCATSTranslator/ReasonerAPI/releases

**Comment by edeutsch** [comment]
I think it would be really helpful to make a new release with this ability before tackling semantic validation.

**Comment by brettasmi** [comment]
Related: https://github.com/NCATSTranslator/reasoner-validator/issues/20  I believe that the resolution of that issue will solve the -beta issue.

**Comment by edeutsch** [comment]
ah, thanks, in fact this is just a duplicate of that issue. I thot I looked for an existing issue before I posted this one, but instead I posted a duplicate.

**Comment by RichardBruskiewich** [comment]
Resolved  by PR https://github.com/NCATSTranslator/reasoner-validator/pull/25
