### ISSUE TITLE
Add support for validating infores keys

### ISSUE THREAD

**Issue by edeutsch** [NCATSTranslator/reasoner-validator#30]
TRAPI refers to infores keys for provenance. There is a spreadsheet of infores keys somewhere. It would be great to ensure that the infores keys listed in a TRAPI document are valid.

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by edeutsch** [comment]
oops, collision with #29

**Comment by RichardBruskiewich** [comment]
Way ahead of you @edeutsch, LOL. I was listening during today's architecture committee call.

**Comment by edeutsch** [comment]
thank you!
