### ISSUE TITLE
Observations from the UI MVP front lines...

### ISSUE THREAD

**Issue by RichardBruskiewich** [NCATSTranslator/reasoner-validator#35]
We create here a 'meta-' issue to generally capture additional validation tasks suggested by the Translator UI (see [session notes and related Andy Crouse slide presentation]( https://docs.google.com/document/d/1HC1XsBhiwtADYiEznVI7TBupb6Q8AxQ7QPcuGTHTUJk
)).

- [ ] Duplicate CURIEs for a given name. Shows some items as a duplicate if there are FDA approved results and non-FDA approved results: _'error' versus 'warning'_? 
    - Are the duplications coming from different KPs? 
    - How would we test for this? 
    - Could we test ARAs for this? 
    - Do we conduct any testing at the level of the ARS itself?
- [x] **Some Missing Names:** results may contain cases where there is no name for a drug (in a TRAPI query for drugs treating diseases...): _'error' versus 'warning'_?
- [ ] Missing (concept) node descriptions: _'error' versus 'warning'_?

**Comment by Genomewide** [comment]
I am going to assign this to the team and get their feedback.

**Comment by RichardBruskiewich** [comment]
Hi Andy (@Genomewide), are the validation issues described here still of interest to you? I'm busy going through older issues to see if there are any loose (validation) ends...

**Comment by RichardBruskiewich** [comment]
@Genomewide, I think TRAPI Responses don't have concept node descriptions. Is this use case now a part of the node annotation service use case (unrelated to TRAPI validation per say)?

**Comment by RichardBruskiewich** [comment]
@Genomewide is the Knowledge Graph Node: model field mandatory for UI? The TRAPI standard says that it is nullable: True (i.e. optional).

**Comment by RichardBruskiewich** [comment]
Detection of missing  names in  release  3.9.0

**Comment by Genomewide** [comment]
is nullable the same as not existing at all? or is that 'name' : null. ?

**Comment by RichardBruskiewich** [comment]
Good question @Genomewide.  I've asked the question before. Here's the (Swagger) definition I know of, but I think the definition includes the situation when the property tag (e.g. **`name:`**)  is  absent:

# Null
OpenAPI 3.0 does not have an explicit null type as in JSON Schema, but you can use nullable: true to specify that the value may be null. Note that null is different from an empty string "".
# Correct
type: integer
nullable: true
# Incorrect
type: null
# Incorrect as well
type:
  - integer
  - null
The example above may be mapped to the nullable types int? in C# and java.lang.Integer in Java. In objects, a nullable property is not the same as an optional property, but some tools may choose to map an optional property to the null value.
```

**Comment by Genomewide** [comment]
Ok. Thanks for all of the feedback.  This really helps and hopefully future-proofs some of the work for us now that I understand the rules better and how they will be checked!

I am closing this as it was not in error in the first place.  No action needed to fix.
