### ISSUE TITLE
Validation error on null relation?

### ISSUE THREAD

**Issue by edeutsch** [NCATSTranslator/reasoner-validator#4]
I am trying to validate this:
https://ars.transltr.io/ars/api/messages/3f7d1b6f-0af2-4884-b334-60602c3ad427

And get this error:
```
- Message INVALID: None is not of type 'string'

Failed validating 'type' in schema['properties']['query_graph']['properties']['edges']['additionalProperties']['properties']['relation']:
    {'description': 'Lower-level relationship type of this edge',
     'example': 'upregulates',
     'type': 'string'}

On instance['query_graph']['edges']['e00']['relation']:
    None
```
apparently on this part:
```
    "query_graph": {
      "edges": {
        "e00": {
          "object": "n01",
          "predicate": "biolink:subclass_of",
          "relation": null,
          "subject": "n00"
        }
      },
```
Are you seeing the same?
What to do about this?

**Comment by patrickkwang** [comment]
Should be fixed by 98a03ce487d529c7aba1e6ac83f2a11c285abd17.

**Comment by edeutsch** [comment]
Great, thanks, let me know when it's all push to PyPI and I'll give it a test!

**Comment by patrickkwang** [comment]
Check out the latest release on PyPI (1.0.2.1.0.1).

**Comment by edeutsch** [comment]
Outstanding! I pip3 installed the latest from PyPI and it runs well and appears to validate nicely. Closing, thanks!
