### ISSUE TITLE
Is this a bug?

### ISSUE THREAD

**Issue by edeutsch** [NCATSTranslator/reasoner-validator#43]
While trying to validate a TRAPI Response with the reasoner_validator version 3.1, I am seeing:
```
  "warnings": [
    {
      "context": "Query Graph",
      "edge_id": "n00--['biolink:physically_interacts_with']->n01",
      "predicate": "biolink:physically_interacts_with",
      "code": "warning.edge.predicate.non_canonical"
    }
  ],
```

What does this mean?
What is wrong with using n00--['biolink:physically_interacts_with']->n01 ?

**Comment by edeutsch** [comment]
note: the follow is being passed to the validator:
```
    trapi_version = '1.3.0'
    biolink_version = '2.2.11'
```

**Comment by RichardBruskiewich** [comment]
Not a bug, simply because reasoner_validator 3.1 does not correctly validate non_canonical predicates in pre-3.0 Biolink. This is a Biolink Model Toolkit validation 0.8.12 coding issue. The 3.0.* versions of reasoner-validator will validate this predicate correctly.
