### ISSUE TITLE
validation fails when results or knowledge_graph are null

### ISSUE THREAD

**Issue by CaseyTa** [NCATSTranslator/reasoner-validator#5]
**Describe the bug**
The spec defines `Message.results` and `Message.knowledge_graph` to be nullable, but validation fails when the results or knowledge_graph are null. 

**To Reproduce**
validate_Response on
```
{
    "datetime": "2021-02-05 23:27:50",
    "description": "Could not map node n01 to OMOP concept",
    "message": {
        "knowledge_graph": null,
        "query_graph": {
            "edges": {
                "e00": {
                    "object": "n01",
                    "predicate": [
                        "biolink:correlated_with"
                    ],
                    "subject": "n00"
                }
            },
            "nodes": {
                "n00": {
                    "category": [
                        "biolink:ChemicalSubstance"
                    ]
                },
                "n01": {
                    "id": [
                        "DOID:90535"
                    ]
                }
            }
        },
        "results": null
    },
    "query_options": {
        "confidence_interval": 0.99,
        "dataset_id": 3,
        "max_results": 5,
        "method": "obsExpRatio",
        "min_cooccurrence": 0
    },
    "reasoner_id": "COHD",
    "schema_version": "1.0.0",
    "status": "CouldNotMapCurieToLocalVocab",
    "tool_version": "COHD 3.0.0"
}
```

**Expected behavior**
Passes validtion.

**Additional context**
Using release version 1.0.2/1.0.1.

**Comment by patrickkwang** [comment]
Thanks, @CaseyTa! This has been fixed in v1.0.3.

**Comment by CaseyTa** [comment]
Thanks, @patrickkwang! This works for me now. 

Should the version now be 1.0.2.1.0.2 instead of 1.0.3.1.0.1? The [docs ](https://reasoner-validator.readthedocs.io/en/latest/)say the TRAPI api version (1.0.2) is written first, followed by the validator library  version.

**Comment by patrickkwang** [comment]
Oh shoot, you're right. The version numbers crossed and I got confused. I think I can straighten it out.

**Comment by patrickkwang** [comment]
Alright, I think I got the version number straightened out. Let me know how that looks, now.

**Comment by CaseyTa** [comment]
Looks good, thanks again!
