### ISSUE TITLE
Why global?

### ISSUE THREAD

**Issue by edeutsch** [NCATSTranslator/reasoner-validator#89]
The following ARAX result: https://arax.ncats.io/devED/api/arax/v1.4/response/dc05d73c-e55f-421c-b6d6-2aa417397537
is producing the following edge from KG2:

```
...
          "object": "MESH:D004852",
          "predicate": "biolink:subclass_of",
          "qualifiers": null,
          "sources": [
            {
              "resource_id": "infores:chebi; infores:genepio; infores:go-plus",
              "resource_role": "primary_knowledge_source",
              "source_record_urls": null,
              "upstream_resource_ids": null
            },
            {
              "resource_id": "infores:rtx-kg2",
              "resource_role": "aggregator_knowledge_source",
              "source_record_urls": null,
              "upstream_resource_ids": [
                "infores:chebi; infores:genepio; infores:go-plus"
              ]
            },
            {
              "resource_id": "infores:arax",
              "resource_role": "aggregator_knowledge_source",
              "source_record_urls": null,
              "upstream_resource_ids": [
                "infores:rtx-kg2"
              ]
            }
          ],
          "subject": "PUBCHEM.COMPOUND:446987"
        },
```

The validator is unhappy because resource_id is not a CURIE. And quite rightly so.

However, the printed message is:
```
Errors:
* Knowledge Graph Edge Sources Retrieval Source Resource Id Infores Not:
=> Infores value is not a valid well-formed CURIE
	$ global
		# infores:chebi; infores:genepio; infores:go-plus:
		- edge_id: 
			PUBCHEM.COMPOUND:446987--biolink:subclass_of->MESH:D004852
```

Why is the context "global"? There's nothing global about this.

It may feel weird to be reporting the provenance of the problem being itself, but I think this should be:

```
=> Infores value is not a valid well-formed CURIE
	$  infores:chebi; infores:genepio; infores:go-plus -> infores:rtx-kg2 -> infores:arax
		# infores:chebi; infores:genepio; infores:go-plus:
		- edge_id: 
			PUBCHEM.COMPOUND:446987--biolink:subclass_of->MESH:D004852
```

As this immediately demonstrates that rtx-kg2 is getting overly creative here.

what do you think?
Can we adjust that?

**Comment by RichardBruskiewich** [comment]
Hi @edeutsch,
As you may have guessed, "global" is a placeholder for validation messages whose context cannot be computed.

Not all validation messages will have source resolution (yet, anyhow). For edges, yes; nodes, probably not. In some cases, the RetrievalSources will also fail to be captured for some reason.

All that said, I see that you've given me a test run whose JSON output I can capture and use for diagnosis. I will take a closer look over the next day or so, single stepping through the validation to see what is going on with **`sources`**  capture.

**Comment by RichardBruskiewich** [comment]
Ah.. I think I see what *might* be an issue:

```json
            {
              "resource_id": "infores:chebi; infores:genepio; infores:go-plus",
              "resource_role": "primary_knowledge_source",
              "source_record_urls": null,
              "upstream_resource_ids": null
            }
```
has a semi-colon delimited set of primary_knowledge_sources. That seems a bit weird considering that the Biolink Model calls for a single primary_knowledge_source. 

I'll have to see what is happening under the hood under such circumstances. It is obviously not a simple CURIE identifier, hence the message.

**Comment by edeutsch** [comment]
> I'll have to see what is happening under the hood under such circumstances. It is obviously not a simple CURIE identifier, hence the message.

yes, that is * why * the message and that's good. But my issue is why the *global*

I'm wondering if the problem is that the code is designed to report the provenance of problems is sources[]. And I think that would be a great feature to add.

**Comment by RichardBruskiewich** [comment]
As I mentioned, "global" is the default if the sources path cannot be computed. In this case, the 

```json
"resource_id": "infores:chebi; infores:genepio; infores:go-plus"
```

was ill-formed by the basic parsing rules. To fix this, I need to introduce the idea of a resource_id (singular) possibly being a semi-colon delimited list of the infores.  I'm not sure what impact that'll have on the code base, but I noted that you are content to keep the full semi-colon delimited string as the **`primary_knowledge_source`** itself, so I'll aim for that.

**Comment by RichardBruskiewich** [comment]
Release 3.7.4 correctly parses semi-colon delimited identifiers so the above issue should go away.
