### ISSUE TITLE
Pass through jsonschema.exceptions.ValidationError

### ISSUE THREAD

**Issue by patrickkwang** [NCATSTranslator/reasoner-validator#9]
It would be nice to be able to `from reasoner_pydantic import validate, ValidationError` rather than having the additional `from jsonschema.exceptions import ValidationError`.

**Comment by RichardBruskiewich** [comment]
This issue was rendered obsolete by the ValidationReporter wrapping of validation, from [**reasoner-validator** release v3.0.0](https://github.com/NCATSTranslator/reasoner-validator/pull/37)
