### ISSUE TITLE
Validation of edge qualifier values is incomplete

### ISSUE THREAD

**Issue by RichardBruskiewich** [NCATSTranslator/reasoner-validator#91]
Edge qualifiers have defined **`qualifier_type_id`** terms which map onto value ranges.

Qualifier values not resolved to their qualifier types will trigger a **Knowledge Graph Edge Qualifiers Qualifier Value** error.

The tricky part of the resolution of such qualifier values is not always directly defined by the qualifier definition itself, but rather, is context sensitive to the particular **`biolink:Association subclass`** that is applicable to the given edge. Hence, before validating qualifier values, one generally needs to know the particular biolink:Association child class in question.

At the moment, the applicable **`biolink:Association`** subclasses are published in the **/meta_knowledge_graph** TRAPI endpoint, and needs to be dynamically mapped to a given edge (by **`subject`**/**`object`** category and perhaps, **`predicate`**, matching?) during validation.

We wish to avoid qualifier value errors if, in fact, the Biolink Model range as defined above, is available.

**Comment by RichardBruskiewich** [comment]
Resolved in https://github.com/NCATSTranslator/reasoner-validator/tree/issue-91-enhance-validation-of-edge-qualifiers, to be released soon once Biolink Model Toolkit 1.1.1 is released, and local poetry dependencies are updated.

**Comment by KevinBretonnelCohen** [comment]
Hello! Is it possible to remove me from this list, please?

**Comment by edeutsch** [comment]
> Hello! Is it possible to remove me from this list, please?

You can remove yourself by going to the repo top page here:
https://github.com/NCATSTranslator/reasoner-validator

and using the Unwatch control to stop getting these emails. Set it to [Ignore]
![image](https://github.com/NCATSTranslator/reasoner-validator/assets/12707718/5051d042-d89e-4084-97fc-3d3d30d9db77)
